return {
--   'nvimtools/none-ls.nvim',
--   dependencies = {
--     'nvimtools/none-ls-extras.nvim',
--     'jayp0521/mason-null.nvim'
--   },
--   config =  function() 
--     require('mason-null-ls').setup {
--       ensure_installed = {
--         'ruff',
--         'prettier',
--         'shfmt'
--       },
--       automatic_installation = true
--     }
--
--
--     local null_ls = require 'null-ls'
--     local sources = {
--       require('none-ls.formatting.ruff').with { extra_args = {'--extend-select', 'I'}},
--       require('non-ls.formatting.ruff_format'),
--       null_ls.builtins.formatting.prettier.with { filetypes = {'json', 'yaml', 'markdown'}}
--     }
--   end
}
