-- local autocmd = vim.api.nvim_create_autocmd
-- local root_name = {".git", "Makefile", }
--
-- autocmd("BufEnter", {
--    pattern = "*",
--    callback = function()
--       local dir = vim.fn.expand("%:p")
--       vim.cmd("silent! lcd " .. dir)
--    end,
-- })
